import fs from 'node:fs';
const path='components/BabylonScene.tsx';
let s=fs.readFileSync(path,'utf8');
s=s.replace("import { factoryStore } from '../store';", "import { factoryStore } from '../store';\nimport { disposeCobotState, syncCobotConfig } from '../babylon/cobot/lifecycle';");
s=s.replace('const cobotStates = new Map<string, CobotState>();','const cobotStates = simState.cobotStates;');
s=s.replace('                    cobotStates.delete(id);','                    const state = cobotStates.get(id);\n                    if (state) disposeCobotState(state);');
const a=s.indexOf('                if (itm) {',s.indexOf('// Sync cobot state'));
const b=s.indexOf('            const activeCobotIds',a);
s=s.slice(0,a)+'                if (itm) syncCobotConfig(cState, itm);\n            }\n'+s.slice(b);
const c=s.indexOf('        function syncCobotStateFromStore(');
const d=s.indexOf('            // Sync gizmo state',c);
s=s.slice(0,c)+'            for (const item of placedItems) {\n                const state = cobotStates.get(item.id);\n                if (state) syncCobotConfig(state, item);\n            }\n\n'+s.slice(d);
s=s.replace('                            state.phase = oldState.phase;',`                            state.program = oldState.program;
                            state.configuredProgramSignature = oldState.configuredProgramSignature;
                            state.simTime = oldState.simTime;
                            state.lastUnlockTime = oldState.lastUnlockTime;
                            state.lastDroppedItemId = oldState.lastDroppedItemId;
                            state.phase = oldState.phase;`);
s=s.replace('if (st.moveModeItemId && gizmoManager.attachedNode) {','if (st.moveModeItemId && gizmoManager.attachedNode instanceof TransformNode) {');
s=s.replace('if (node) {\n                        const targetItem', 'if (node instanceof TransformNode) {\n                        const targetItem');
s=s.replace('camera.inputs.attached.pointers.buttons = [0, 2];','(camera.inputs.attached.pointers as ArcRotateCameraPointersInput).buttons = [0, 2];');
s=s.replace('Engine, Scene, ArcRotateCamera, Vector3,', 'Engine, Scene, ArcRotateCamera, ArcRotateCameraPointersInput, Vector3,');
s=s.replace('                    const w = rtt!.getSize().width;', '                    const pixelBytes = new Uint8Array(pixels.buffer, pixels.byteOffset, pixels.byteLength);\n                    const w = rtt!.getSize().width;');
s=s.replaceAll('pixels[src + i', 'pixelBytes[src + i');
fs.writeFileSync(path,s);
const entity='babylon/entityMeshes.ts';
fs.writeFileSync(entity,fs.readFileSync(entity,'utf8').replace(/^.*\.castShadows = true;.*\r?\n/gm,''));
